---
- name: Clone node repo
  git:
    repo: '{{ sui_repo }}'
    dest: '{{ sui_directory }}'
    version: '{{ sui_version }}'
    update: true
    force: true
    recursive: false

- name: Build node binary
  command: '{{ item }}'
  args:
    chdir: '{{ sui_directory }}'
  with_items:
    - 'nice -n 10 cargo clean'
    - 'nice -n 10 cargo build --release'
  environment:
    PATH: '{{ path }}'

- name: Copy binaries
  become: true
  copy:
    src: '{{ sui_directory }}/target/release/{{ item }}'
    dest: '/usr/local/bin'
    owner: root
    group: root
    mode: 0755
    remote_src: true
  loop:
    - sui-node
